# Generated by Django 3.2.7 on 2022-07-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'موتر', 'verbose_name_plural': 'موتر ها'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'مقصد', 'verbose_name_plural': 'مقصد ها'},
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='chairs',
            field=models.IntegerField(default=0, verbose_name='چوکی های که با قی مانده'),
        ),
        migrations.AlterField(
            model_name='car',
            name='expire_time',
            field=models.DateTimeField(verbose_name='زمان حرکت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_system.goal', verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام موتر'),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_chairs',
            field=models.IntegerField(default=0, verbose_name='تمام چوکی ها'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_province',
            field=models.CharField(max_length=120, verbose_name='به ولایت'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='province',
            field=models.CharField(max_length=200, verbose_name='از ولایت'),
        ),
    ]
