# Generated by Django 3.2.7 on 2022-07-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0002_auto_20220720_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='chairs',
            field=models.IntegerField(default=0, verbose_name='چوکی های فروخته شده'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='ticket/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_system.car')),
            ],
        ),
    ]
