# Generated by Django 3.2.7 on 2022-07-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0003_auto_20220721_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکیت', 'verbose_name_plural': 'تیکیت ها'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='chair_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_system.car', verbose_name='موتر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='تخلص'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ticket/', verbose_name='فایل تیکیت'),
        ),
    ]
